### PR TITLE
Fix SMS-based 2FA

### LINKED ISSUE #38: 2FA auth doesn't work with SMS-based 2FA
It's not clear to me what makes GitHub send you a text message.

Evidence (https://github.com/sigmavirus24/github3.py/issues/387, https://github.com/github/hub/commit/3d299896f4a3c2ee38a80c8f03ac9d23079eb045) is that attempting to create an authorization is required.  But.... I though [we _were_](https://github.com/umts/dev-training/blob/6c39f2b78953061d1770e8764a8efa55d3d12e18/lib/umts_training/client.rb#L37)?

This will require a little experimentation.

### PR DESCRIPTION
**Pull request by werebus**
SMS-based 2FA doesn't send a text message unless you're trying to create an authorization. The first thing we try to do is list existing ones and delete any possible duplicates. The work-around is to just send a dummy request first.

Closes #38 

It _does_ sometimes send you two text messages now, but I'm inclined to say, "good enough" given that all this code is going to have to go away in November anyways (#35)

* [x] RSpec and Rubocop were run (`rake`)
* [x] Test coverage is good
* [x] Documentation was updated if public methods changed (`rake rerdoc`)

### CODE REVIEW

File: spec/support/password_client.rb [hunk 1]
```diff
@@ -10,6 +10,8 @@ def initialize(password: 'GOOD')
   end
 
   def create_authorization(params = {})
+    raise Octokit::UnprocessableEntity if params[:note].nil?
```
Comment (Anbranin) [inline spec/support/password_client.rb:13]: I'm sorry I'm lost why are you raising this exception here and then just handling it with nothing later?

Comment (werebus) [reply spec/support/password_client.rb:13]: I'm raising it here because that's what GitHub does.

However, this is one of those times:

1.  Encounter bug
2.  Fix bug 1
3.  Encounter bug
4.  Fix bug 3 in a way that makes bug 1 irrelevant.

That said, this mock is a little more accurate _with_ this line than without it (could be better).

In cases where the user _has_ 2FA setup, the new "dummy" attempt at creating an authorization raises an `Octokit::OneTimePasswordRequired`. But in cases where they _don't_ it raises an `Octokit::UnproccesableEntity` because the `note` is required.

Comment (werebus) [reply spec/support/password_client.rb:13]: really it should be something like:

```ruby
if @password == 'TFA' && !params.dig(:headers, 'X-Github-OTP')
  raise Octokit::OneTimePasswordRequired
end

if @password == 'GOOD' || @password == 'TFA'
  if params[:note].nil?
    raise Octokit::UnprocessableEntity
  else
    OpenStruct.new(token: '*')
  end
else
    raise Octokit::Unauthorized
end
```

But...

Comment (werebus) [reply spec/support/password_client.rb]: Nope, still not right.

File: spec/support/password_client.rb [hunk 2]
```diff
@@ -10,14 +10,13 @@ def initialize(password: 'GOOD')
   end
 
   def create_authorization(params = {})
-    if @password == 'GOOD' ||
-       @password == 'TFA' && params.dig(:headers, 'X-Github-OTP')
-      OpenStruct.new(token: '*')
-    elsif @password == 'TFA'
+    raise Octokit::Unauthorized if @password != 'GOOD' && @password != 'TFA'
```
Comment (Anbranin) [inline spec/support/password_client.rb:13]: I think this should be an `unless` but it also really doesn't matter.

File: spec/support/password_client.rb [hunk 3]
```diff
@@ -10,7 +10,7 @@ def initialize(password: 'GOOD')
   end
 
   def create_authorization(params = {})
-    raise Octokit::Unauthorized if @password != 'GOOD' && @password != 'TFA'
+    raise Octokit::Unauthorized unless %w[GOOD TFA].include? @password
```
Comment (Anbranin) [inline spec/support/password_client.rb:13]: 👍
